name: Repo Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (valfritt men bra) välj python3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Validate presence
        run: |
          test -f journal/DeveloperJournal.md
          test -f tasks/ProjectTasks.md
          test -f docs/ProjectInformation.md

      - name: Validate tasks format
        shell: bash
        run: |
          python3 - <<'PY'
          import re, sys
          txt = open('tasks/ProjectTasks.md','r',encoding='utf-8').read()
          blocks = re.findall(r"- TASK:\s*(.+?)\n\s*owner:\s*(.+?)\n\s*status:\s*(.+?)\n\s*notes:\s*(.*?)(?:\n\n|$)", txt, flags=re.S)
          if not blocks:
              print("No task blocks found"); sys.exit(1)
          valid = {'TODO','IN_PROGRESS','REVIEW','DONE','BLOCKED','NEEDS_INFO'}
          for title, owner, status, notes in blocks:
              title = title.strip(); status = status.strip()
              if not title:
                  print("Empty task title"); sys.exit(2)
              if status not in valid:
                  print("Invalid status for task '%s': %s" % (title, status)); sys.exit(3)
          print("Tasks OK")
          PY

      - name: Validate mandatory notices acknowledged
        shell: bash
        run: |
          python3 - <<'PY'
          import re, sys
          txt = open('docs/ProjectInformation.md','r',encoding='utf-8').read()
          notices = re.findall(r"- (NOTICE-\d{4}-\d{2}-\d{2}):\s*\".*?\"\s*\n\s*- Effective: .*?\n\s*- Mandatory: (Yes|No)\s*\n\s*- Action Required.*?\n\s*- Acknowledged by:\s*\n(.*?)(?:\n\n|$)", txt, flags=re.S)
          ok = True
          for nid, mand, ack in notices:
            if mand == 'Yes':
              lines = [l.strip() for l in ack.strip().splitlines() if l.strip().startswith('-')]
              if not lines:
                print("Mandatory notice %s has no acknowledgments" % nid)
                ok = False
          if not ok: sys.exit(4)
          print("Notices OK")
          PY
